services:
  api-gateway:
    build: ./services/api-gateway
    container_name: unilib-api-gateway
    ports:
      - "8080:8080"
    environment:
      USER_SERVICE_URL: http://user-service:3001
      BOOK_SERVICE_URL: http://book-catalog-service:3002
      LOAN_SERVICE_URL: http://loan-service:3003
      NOTIFICATION_SERVICE_URL: http://notification-service:3004
    depends_on:
      - user-service
      - book-catalog-service
      - loan-service
      - notification-service

  user-service:
    build: ./services/user-service
    container_name: unilib-user-service
    ports:
      - "3001:3001"
    env_file:
      - ./services/user-service/.env

  book-catalog-service:
    build: ./services/book-catalog-service
    container_name: unilib-book-catalog-service
    ports:
      - "3002:3002"
    env_file:
      - ./services/book-catalog-service/.env

  loan-service:
    build: ./services/loan-service
    container_name: unilib-loan-service
    ports:
      - "3003:3003"
    env_file:
      - ./services/loan-service/.env
    environment:
      BOOK_SERVICE_URL: http://book-catalog-service:3002
      NOTIFICATION_SERVICE_URL: http://notification-service:3004
    depends_on:
      - book-catalog-service
      - notification-service

  notification-service:
    build: ./services/notification-service
    container_name: unilib-notification-service
    ports:
      - "3004:3004"
    env_file:
      - ./services/notification-service/.env
    environment:
      LOAN_SERVICE_URL: http://loan-service:3003
      USER_SERVICE_URL: http://user-service:3001

  frontend:
    build:
      context: ./frontend
      args:
        VITE_API_GATEWAY_URL: /api
    container_name: unilib-frontend
    ports:
      - "3000:80"
    depends_on:
      - api-gateway
