sonar.projectKey=HemoraSLIIT_UniLib
sonar.organization=hemorasliit
sonar.projectName=UniLib

sonar.sources=frontend/src,services/api-gateway/src,services/user-service/src,services/book-catalog-service/src,services/loan-service/src,services/notification-service/src
sonar.exclusions=**/node_modules/**,**/dist/**,**/coverage/**,**/*.png
